### ISSUE TITLE
[Feature Request] Provides option to disable line-numbers and/or header

### ISSUE THREAD

**Issue by kwaa** [Microflash/rehype-starry-night#2]
Nice plugin! As the title suggests.

Also, I was wondering if you would be interested in implementing in-line highlighting like `rehype-pretty-code`?

**Comment by naiyerasif** [comment]
The initial scope of this plugin was to show line numbers and header; that's why there's no option to disable them. However, you can hide them with the following CSS.

```css
.highlight .highlight-header,
.highlight .line-number {
  display: none;
  visibility: hidden;
}
```

> Also, I was wondering if you would be interested in implementing in-line highlighting like `rehype-pretty-code`?

To implement inline highlighting, I'd have to introduce some sort of non-standard language annotation syntax for inline code element in the markdown, which is well beyond the scope of this plugin. However, if such a syntax becomes a standard in future, I'd be happy to support it.
